Repository codingstuff91/asgard_table_manager, pull requests merged in 2023-10, with the labels that each got.

#32 Added confirm prompt for users
  resources/views/day/show.blade.php
Labels: improvment

#39 Fixed duplicate game creation
  app/Http/Requests/GameStoreRequest.php
  resources/views/game/create.blade.php
  tests/Feature/Http/Controllers/GameControllerTest.php
Labels: bug

#40 Fixed table creation problem
  resources/views/components/input-label.blade.php
  resources/views/components/text-input.blade.php
  resources/views/table/create.blade.php
Labels: bug

#35 Added automatic registration of organizer after table creation
  app/Actions/UserSubscriptionAction.php
  app/Http/Controllers/TableController.php
  tests/Feature/Actions/UserSubscriptionActionTest.php
  tests/Feature/Http/Controllers/TableControllerTest.php
Labels: improvment

#41 Updated readme file
  README.md
Labels: improvment

#43 Applied pint styles corrections
  app/Console/Kernel.php
  app/DataObjects/TableData.php
  app/Events/TableCreated.php
  app/Events/TableDeleted.php
  app/Events/TableUpdated.php
  app/Events/UserTableSubscribed.php
  app/Events/UserTableUnsubscribed.php
  app/Http/Controllers/Auth/NewPasswordController.php
  app/Http/Controllers/Auth/PasswordResetLinkController.php
  app/Http/Controllers/DayController.php
  app/Http/Controllers/GameController.php
  app/Http/Controllers/TableController.php
  app/Http/Requests/GameStoreRequest.php
  app/Http/Requests/TableStoreRequest.php
  app/Http/Requests/storeDayRequest.php
  app/Listeners/TableCreatedDiscordNotification.php
  app/Listeners/TableDeletedDiscordNotification.php
  app/Listeners/TableUpdatedDiscordNotification.php
  app/Listeners/UserSubscriptionDiscordNotification.php
  app/Listeners/UserUnsubscriptionDiscordNotification.php
  app/Models/Category.php
  app/Models/Day.php
  app/Models/Game.php
  app/Models/Table.php
  app/Models/User.php
  app/Services/DiscordService.php
  config/discord.php
  database/factories/DayFactory.php
  database/factories/GameFactory.php
  database/factories/TableFactory.php
  database/migrations/2023_04_24_093811_add_admin_column_into_users_table.php
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DaySeeder.php
  database/seeders/GameSeeder.php
  database/seeders/UserSeeder.php
  pint.json
  routes/auth.php
  routes/web.php
  tests/Feature/Http/Controllers/DayControllerTest.php
  tests/Feature/Http/Controllers/GameControllerTest.php
  tests/Feature/Http/Controllers/TableControllerTest.php
  tests/Unit/Services/DiscordServiceTest.php
Labels: improvment

#45 Refactorization of sending discord notification process
  app/Actions/Discord/BuildEmbedMessageStructureAction.php
  app/Actions/Discord/CreateDiscordNotificationAction.php
  app/Actions/Discord/DefineChannelIdAction.php
  app/Actions/Discord/SendDiscordNotificationAction.php
  app/DataObjects/DiscordNotificationData.php
  app/Enums/EmbedColor.php
  app/Enums/EmbedMessageContent.php
  app/Events/TableCreated.php
  app/Events/TableDeleted.php
  app/Events/TableUpdated.php
  app/Events/UserTableSubscribed.php
  app/Events/UserTableUnsubscribed.php
  app/Http/Controllers/TableController.php
  app/Listeners/TableCreatedDiscordNotification.php
  app/Listeners/TableDeletedDiscordNotification.php
  app/Listeners/TableUpdatedDiscordNotification.php
  app/Listeners/UserSubscriptionDiscordNotification.php
  app/Listeners/UserUnsubscriptionDiscordNotification.php
  app/Services/DiscordService.php
  composer.json
  config/discord.php
  routes/web.php
  tests/Feature/Actions/BuildEmbedMessageStructureActionTest.php
  tests/Feature/Actions/DefineChannelIdActionTest.php
  tests/Feature/Actions/SendDiscordNotificationActionTest.php
  tests/Feature/Http/Controllers/TableControllerTest.php
  tests/Pest.php
Labels: refacto
